### ISSUE TITLE
Create image for sirepo testing

### ISSUE THREAD

**Issue by robnagler** [radiasoft/container-sirepo-ci#1]
https://github.com/radiasoft/sirepo/runs/6777623335?check_suite_focus=true

> ERROR [launcher]: No binary for ChromeHeadless browser on your platform.
>  Please, set "CHROME_BIN" env variable.

We need a docker image based off beamsim that has chrome and karma and other things needed by sirepo

**Comment by robnagler** [comment]
@rorour I would like you to take a stab at this. Please look at container-python3 for a simple repo example, and create a skeleton in https://github.com/radiasoft/container-sirepo-ci.

**Comment by e-carlin** [comment]
@rorour if it is possible please install slurm ([radia_run slurm-dev](https://github.com/radiasoft/download/blob/3ae712a2cdfb3f13fd8c000c53dad3deb20ba217/installers/slurm-dev/radiasoft-download.sh) should work) in the image. If it is installed then [sbatch_test](https://github.com/radiasoft/sirepo/blob/b72939a86417211e1c71f1e5fa1e033d12122805/tests/sbatch_test.py) runs (sentinel is [here](https://github.com/radiasoft/sirepo/blob/b72939a86417211e1c71f1e5fa1e033d12122805/tests/conftest.py#L103)). It would be good for this test to run in ci since some (most) folks on our team don't have slurm installed locally so the test doesn't run for them.
